### ISSUE TITLE
REST API explorer for 6.2.2

### ISSUE THREAD

**Issue by jberthoux** [Alfresco/rest-api-explorer#117]
Hello,

just a question, could you tell me what version is corresponding to ACS 6.2.2?
Thank you in advance.

Regards,
Julien

**Comment by montgolfiere** [comment]
JFYI: you can x-check which version of REST API Explorer was bundled in ACS 6.2.2 via ACS Packaging release tag, eg.

https://github.com/Alfresco/acs-packaging/blob/acs-packaging-6.2.2/pom.xml#L55
=>
https://github.com/Alfresco/rest-api-explorer/releases/tag/6.2.1.1
