### ISSUE TITLE
Is the API hosted

### ISSUE THREAD

**Issue by covolution** [Alfresco/rest-api-explorer#165]
Hello 👋
I googled the API and got this url https://api-explorer.alfresco.com/ 

Is the API still hosted or is there only this repo now?

**Comment by jottley** [comment]
Hi Gethin!

I think you are looking for the Javadoc. The hosted Javadoc is no longer published online.  You can grab the Javadoc jar files from nexus if you need them.  

Jared

**Comment by jottley** [comment]
ok.  It is shipped with each release.  We are working on getting the one you link to updated to the latest release.
