### ISSUE TITLE
Missing pagination support for listSourceAssociations and listTargetAssociations

### ISSUE THREAD

**Issue by saidone75** [Alfresco/rest-api-explorer#192]
Hello,

I've found that skipCountParam and maxItemsParam are missing from listSourceAssociations and listTargetAssociations.
This seem to also affect the Java REST API https://github.com/Alfresco/alfresco-java-sdk making impractical to fetch associations in excess of the first 100.

Thanks,
Marco

**Comment by tpage-alfresco** [comment]
I created the PR for this here: https://github.com/Alfresco/rest-api-explorer/pull/199

I realised afterwards that you made an identical commit, and if you'd made a PR (and signed the contribution agreement) we could have accepted it. Sorry - I should have made that more clear.

Thanks for your help raising and investigating this issue!
