### ISSUE TITLE
[Typo Issue] OperationId RemoveFavorite instead of RemoveFavoriteSite

### ISSUE THREAD

**Issue by jmpascal** [Alfresco/rest-api-explorer#6]
Aloah,

There's a typo issue for Remove Favorite operationId. [Shortcut](https://github.com/Alfresco/rest-api-explorer/blob/develop/src/main/webapp/definitions/alfresco-core.yaml#L2988)

Currently it's **removeFavoriteSite**
It should be **removeFavorite**

During autogeneration it's important ;)

My 2 cts.

**Comment by montgolfiere** [comment]
Thanks for the feedback. Fixed: https://github.com/Alfresco/rest-api-explorer/commit/49df8822097f1a59a078d3dc87f9ca9921dcf435
